MountPointName: Mount point name
UpdateMap: Update map
AccessDeniedAdminsOnly: Only administrators have access to this page. Please log in with an administrator account
LoginPlease: Please log in to access this page
Users: Users
Email: E-mail
ResetPassword: Reset password
RestoreLogin: Restore login
Password: Password
Username: Username
SignOut: Sign out
SignIn: Sign in
ValueOfIndicator x@Text: The value of the indicator #{x} 
TemperatureValue: Temperature value
Test: Test
Report: Report
EnterYourQuery: Enter your query
Crashes: Crashes
Home: Home