MountPointName: Название точки монтирования
UpdateMap: Обновить карту
AccessDeniedAdminsOnly: Доступ к этой странице имеют только администраторы. Пожалуйста, войдите под учетной записью администратора
LoginPlease: Пожалуйста, войдите для доступа к этой странице
Users: Пользователи
Email: E-mail
ResetPassword: Сбросить пароль
RestoreLogin: Восстановить вход
Password: Пароль
Username: Логин
SignOut: Выйти
SignIn: Войти
ValueOfIndicator x@Text: Значение показателя #{x}
TemperatureValue: Значение температуры
Test: Тест
Report: Отчет
EnterYourQuery: Введите ваш запрос
Crashes: Сбои
Home: Главная